stages:
  - linters
  - build

flutter_linters:
  stage: linters
  image: ghcr.io/cirruslabs/flutter:latest
  script:
    - cd dillearning
    - flutter pub get
    - flutter analyze
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

backend_linters:
  stage: linters
  image: python:3.12
  before_script:
    - pip install tox
  script:
    - tox
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

create_frontend_deb:
  stage: build
  image: ghcr.io/cirruslabs/flutter:latest
  script:
    - scripts/create_frontend_deb_package.sh
  artifacts:
    paths:
      - dillearning/build/linux/x64/release/bundle/*.deb
    expire_in: 1 week
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push"'
