[vars]
MODULE_FOLDER = dillearning-backend 

[tox]
envlist = flake,
          isort,
          black,

skipsdist = true

[testenv]
basepython = 3.12

# https://pypi.org/project/flake8/
[testenv:flake]
deps = flake8
commands = flake8 {[vars]MODULE_FOLDER}

# https://pypi.org/project/isort/
[testenv:isort]
deps = isort
commands = isort .

# https://pypi.org/project/black/
[testenv:black]
deps = black
commands = black .

[flake8]
max-line-length = 88
exclude = venv,.tox,.git,build,dist
